# Generated by Django 4.1.3 on 2022-11-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
